apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: default
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        namespace: default
    spec:
      containers:
        - name: api-service
          image: "malkev1ch/api-service:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ADDRESS
              value: '0.0.0.0:8080'
            - name: USER_SERVICE_ADDRESS
              value: 'user-service:80'

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: api-service
