apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-voucher-service
  namespace: default
  labels:
    app: voucher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voucher-service
  template:
    metadata:
      labels:
        app: voucher-service
        namespace: default
    spec:
      containers:
        - name: voucher-service
          image: europe-docker.pkg.dev/tactical-works-402510/demo/voucherservice:COMMIT_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ADDRESS
              value: '0.0.0.0:8080'
            - name: POD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_ADDRESS
              value: $(POD_HOST):4317

---
apiVersion: v1
kind: Service
metadata:
  name: svc-voucher-service
  namespace: default
spec:
  selector:
    app: voucher-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort

